### ISSUE TITLE
Re-use SecureRandom.

### ISSUE THREAD

**Issue by rzwitserloot** [amdelamar/jhash#2]
https://github.com/amdelamar/jhash/blob/master/src/main/java/com/amdelamar/jhash/util/HashUtils.java#L33

Creating a new SecureRandom is probably not as good an idea as having a single instance, or even a `ThreadLocal<SecureRandom>` (I'm not actually sure if SR is threadsafe. It probably is).

**Comment by amdelamar** [comment]
Seems like its safe. Taking this excerpt from SO:

> Yes, it is. It extends Random, which was always had a de facto threadsafe implementation, and, from Java 7, explicitly guarantees threadsafety. https://stackoverflow.com/a/1461624

I'll add a `randomSalt( SecureRandom )` method for good measure.
