### ISSUE TITLE
Support bcrypt revision 2b

### ISSUE THREAD

**Issue by deletescape** [amdelamar/jhash#27]
I'm migrating from a python backend to the jvm and would love to use this library. Most of my hashes however are currently using the 2b revision of bcrypt. This version bump technically only applied to the openBSD implementation and should be functionally identical with 2a everywhere else. It should be possible to handle it just like 2y.

For now I will just replace the $2b with $2a in all my fields as a workaround.

**Comment by amdelamar** [comment]
Ok this should be fixed in `2.1.2`. Thanks!
