### ISSUE TITLE
API is unfriendly due to overuse of checked exceptions.

### ISSUE THREAD

**Issue by rzwitserloot** [amdelamar/jhash#3]
https://github.com/amdelamar/jhash/blob/master/src/main/java/com/amdelamar/jhash/Hash.java#L72

https://github.com/amdelamar/jhash/blob/master/src/main/java/com/amdelamar/jhash/Hash.java#L53

Seems like bad API design to throw a (checked!) exception in the signature that can't actually happen unless your implementation is corrupt. You might as well throw an InternalError. Catch and rethrow as runtime exception (because it can't happen). Corrupt / weirdly configured JDKs might not have the appropriate algorithms in their built in security library, but a checked exception is still a bad design decision here: A user of a library trying to go with your defaults will not be able to meaningfully recover from such an error, so what are they going to put in their catch block?

https://github.com/amdelamar/jhash/blob/master/src/main/java/com/amdelamar/jhash/exception/InvalidHashException.java#L3

This should be a runtimeexception. Comes down to the same problem: If I were to write code that uses this library, and this exception occurs, what am I going to do? 99.95% of the time, what I want to do is blow the current execution stack with an exception explaining what exotic bad thing just happened. Passing on the very exception _YOU_ throw (because the library is the best at generating a message, presumably) accomplishes just that, but being checked makes that hard for me. Sure, it's theoretically possible a corrupt hash is an expectable condition that can be recovered from, but that's a really exotic use case. Think about it: There are really only 4 possible scenarios here:

* Your own library has a bug (such as what happens with passing in PBKDF2Gobbledygook as algorithm, then InvalidHashEx would happen). There's nothing sane I can do here. You can't use checked exceptions to make calling code somehow deal with your bugs.
* There's a version mismatch and your library changed the scheme of that hash between versions. Similarly, nothing sane I can do but 'log it and exit', which just propagating that exception will do in a far superior way than forcing every caller to try to do that.
* The JVM is corrupt. In which case all bets are off anyway.
* The data in the DB got overwritten or corrupted. In which case all bets are off anyway.

Checked exceptions are for somewhat expectable conditions that one assumes can be recovered from. Let me put it this way: InternalError isn't checked either.

**Comment by amdelamar** [comment]
Exception handling has been cleaned up in 2.0.0
