### ISSUE TITLE
Consider using the builder pattern for Hash.create.

### ISSUE THREAD

**Issue by rzwitserloot** [amdelamar/jhash#4]
https://github.com/amdelamar/jhash/blob/master/src/main/java/com/amdelamar/jhash/Hash.java#L180

You've got 10 methods called 'create' here, and some of the paramtypes are the same. This is going to cause confusion and it's unclear what/how to use this. My advice:

Have 1 convenience method that just takes a single String, and then have a builder kind of deal. Instead of:

`Hash.create("pass", "pepper", 13)`, I'd write: `Hash.create().password("pass").pepper("pepper").complexityFactor(13).build()`.

 `parameter` is not clear enough as to the intent of that variable. The named methods ensure everyone can at a glance see what's going on, IDE autocomplete will guide you as to what you can do and lets you write javadoc for each element, and while that's more code to write, you don't actually specify pepper, rounds, algorithm, etc, unless it's important to do so (you'd go with the default choices if it's not), so apparently these things are important, which means: It's good that they are all explicitly named like this.

Note, if I were to write:

`Hash.create("pepper", "pass", 13)`, the code compiles and runs without warnings or errors, and yet that doesn't do what I expected (I flipped the pepper and pass args). There's no way I can easily tell I messed that up. Had I written: `Hash.of().password("pepper").pepper("password").create()`, I can visually identify I'm doing it wrong, and it's highly unlikely I'd ever  make that mistake in the first place.

**Comment by amdelamar** [comment]
Java Builder pattern has been implemented in 2.0.0
