### ISSUE TITLE
Bug: Passing unknown algo string that starts with PBKDF2.

### ISSUE THREAD

**Issue by rzwitserloot** [amdelamar/jhash#5]
https://github.com/amdelamar/jhash/blob/master/src/main/java/com/amdelamar/jhash/Hash.java#L269

There's a bug here: If I pass algorithm `"PBKDF2withGobbledygook"`, I'm supposed to get a `NoSuchAlgorithmException("Unsupported algorithm type.")`, but I won't. Instead the operation works but produces an unverifiable invalid value.

**Comment by amdelamar** [comment]
Won't be possible after I release a new version that uses `Type enum` instead of `Strings`.
