### ISSUE TITLE
char[] to String conversion is breaking admittedly overblown security principle.

### ISSUE THREAD

**Issue by rzwitserloot** [amdelamar/jhash#6]
https://github.com/amdelamar/jhash/blob/master/src/main/java/com/amdelamar/jhash/Hash.java#L265

**This is a security issue** – the reason you sometimes see passwords/salts passed as char arrays, and not Strings, is that Strings are impossible to securely eliminate from the process; they don't disappear until they get GCed and might even end up interned someplace. You can't wipe their contents either. If you eliminate the content of a char array (`Arrays.fill(charArray, '\0')`), you've got a better chance of eliminating the content from memory introspection tools. This is a pretty exotic security measure (if some process gets to look into your JVM process internals, you've got problems!), but nevertheless, that is why things like JPasswordField and such work with char[]. By having char[] based arguments in the first place you're creating the illusion that you're supportive of this security protocol, but you're not, as you're making strings out of em. Either eliminate the char[] based methods, OR document with all sorts of `<blink>` tags and other such 'HERE BE DRAGONS!' (you can tell I'm not a fan of this plan) that you're writing a check your code can't cash, OR _BOTH_ stop turning them into strings, wipe all the char[] arrays you make yourself, and either wipe the input param char array or document that caller should take care of that ASAP. Do a global search for String to find all cases of this, same for char[].

**Comment by amdelamar** [comment]
I see your point. Do you think I should remove all `String password` argument methods and force `char[]` arguments and returns only?

**Comment by rzwitserloot** [comment]
No, keep the strings.

Sometimes some library enforces strings upon you (you're using a web framework that passes incoming form submits via string to you), and then rewriting to char[] in your own code is again creating an impression that is a lie. Best to leave em as strings.

Normally you could consider the point that this is a security faux pas and it's better to force the programmer using your library to eliminate all string-based passwords, but plenty of people (like me) rate the security risk of storing crypto in strings as extremely low and not worth massive rewrites.

**Comment by amdelamar** [comment]
Passwords and Peppers are char[] now. Hash outputs are Strings still because most any application that uses this library will store the hash output in their database/storage via String and not char[] anyway.
