### ISSUE TITLE
Question: Compatibility with jeremyh version of BCrypt

### ISSUE THREAD

**Issue by 64696765** [amdelamar/jhash#9]
Compatibility with https://github.com/jeremyh/jBCrypt

It looks like the generated hashes are not compatible
to jeremyh version of BCrypt

String yourHash = BCrypt.create("password", 12);
String theirHash = BCrypt.hashpw("password", BCrypt.gensalt (12));

Assert.assertTrue(BCrypt.checkpw("password", yourHash)) -> FALSE

String testHash = BCrypt.create("password", theirHash, 12);
Assert.assertTrue (HashUtils.slowEquals (theirHash.getBytes(), testHash.getBytes())) -> FALSE

Where is my mistake?

**Edit**
BCrypt Tester: https://www.dailycred.com/article/bcrypt-calculator
theirHash -> Password and hash match
yourHash -> Password and hash do NOT match

**Comment by amdelamar** [comment]
Its the salt lengths.

jBCrypt uses the normal 16 byte length. While JHash uses 24 byte length.
>(And Your bcrypt-calculator probably uses 16 too, but it doesn't explicitly state that.)

Actually, you helped identify a problem with JHash as a result. `Hash.SALT_BYTE_SIZE` should be changeable and not final. It also means some offset counting in BCrypt.class needs to be fixed to accept varying salt lengths if it were to change. I'll have to fix that. Thanks for pointing it out!

**Comment by 64696765** [comment]
Thank you for your answer.
You're right, the salt length is different. I probably overlooked that.
A variable salt length is a good idea and makes sense.

**Comment by amdelamar** [comment]
BCrypt salt length defaults to 16 now, but can now be changed in v2.0.0  15e94eb
